## 一 异常处理

#### 1.1 throw

```dart
// 抛出固定类型的异常
throw new FormatException('Expected at least 1 section');

// 抛出任意类型的异常
throw 'Out of llamas!';
```

因为抛出异常属于表达式，可以将throw语句放在=>语句中，或者其它可以出现表达式的地方:
```dart
 distanceTo(Point other) =>
     throw new UnimplementedError();
```

#### 1.2 catch

将可能出现异常的代码放置到try语句中，可以通过 on语句来指定需要捕获的异常类型，使用catch来处理异常。
```dart
 try {
    breedMoreLlamas();
 } on OutOfLlamasException {
    // A specific exception
    buyMoreLlamas();
 } on Exception catch (e) {
    // Anything else that is an exception
    print('Unknown exception: $e');
 } catch (e, s) {
    print('Exception details:\n $e');
    print('Stack trace:\n $s');
 }
```

#### 1.3 rethrow
rethrow语句用来处理一个异常，同时希望这个异常能够被其它调用的部分使用。
```dart
final foo = '';

 void misbehave() {
    try {
      foo = "1";
    } catch (e) {
      print('2');
      rethrow;// 如果不重新抛出异常，main函数中的catch语句执行不到
    }
 }

 void main() {
    try {
      misbehave();
    } catch (e) {
      print('3');
    }
 }

```

#### 1.4 finally
Dart的finally用来执行那些无论异常是否发生都执行的操作。
```dart
final foo = '';

  void misbehave() {
    try {
      foo = "1";
    } catch (e) {
      print('2');
    }
  }

  void main() {
    try {
      misbehave();
    } catch (e) {
      print('3');
    } finally {
      print('4'); // 即使没有rethrow最终都会执行到
    }
  }
```

